### PR TITLE
Add Finnish localization

### PR DESCRIPTION
**Pull request by Mikaela**

### CODE REVIEW

**Comment by Mikaela** [comment]
Will I need to escape `{ä,ö,å}` and do you have any recommendation on ensuring string validity? I am working in `codium --diff en.json fi.json`.

I am not used to translating json files directly and have concerns on keeping them up-to-date, while generally projects I contribute to through translations use Weblate or GNU/Gettext which I translated through PoEdit.

**Comment by J-Rios** [comment]
Hi,

For checking if the JSON file is valid, there is a python script in source directory that you can run:

```bash
cd TLG_JoinCaptchaBot/sources
python3 langcheck.py
```

Maybe I should add some GitHub action workflow to run that script automatically on CI when a Pull Request is received...

**Comment by J-Rios** [comment]
I'm not sure if that characters need to be escaped, but if you run the langcheck script and see that it is needed, just add a back-slash character before any of them:
"ATTR" : "Ex\ämple text f\ôr char\åcters"

**Comment by Mikaela** [comment]
I had errornesously added new lines to the beginning, but now `python3 langcheck.py` passes and everything should be translated. Do you have an option to squashwith GitHub or should I squash the commits locally?

**Comment by J-Rios** [comment]
No problem, GitHub allows to select the merge procedure to apply, "Merge Commit", "Squash Merge" or "Rebase Merge", so I will merge squashing into a single commit.

One last thing, is ok if I put your name (or username) into language contributors list in the Readme file?

**Comment by Mikaela** [comment]
> One last thing, is ok if I put your name (or username) into language contributors list in the Readme file?

I guess so, probably as Aminda Suomalainen (@Mikaela), judging by the other entries

**Comment by Mikaela** [comment]
unless they are Telegram usernames in which case I am https://t.me/AmindaEU

**Review by J-Rios — APPROVED** [review]
Perfect, thanks for the contribution!

I will enable the Finnish language and update my Bot instances (@join_captcha_bot and @pro_join_captcha_bot) in short time.

Best Regards.

**Pull request merged**
