### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by nidamanx**
- Italian language 
- apt vs apt-get
- restart always for docker container

### CODE REVIEW

**Comment by J-Rios** [comment]
Wasn't this Pull Request being accepted and merged in may?

https://github.com/J-Rios/TLG_JoinCaptchaBot/pull/100

**Comment by nidamanx** [comment]
> Wasn't this Pull Request being accepted and merged in may? Seems that this changes are already available in current commit.
> 
> Please check:
> #100

Yes, seemply you're right
The strange is that I cannot merge (update my fork with your new editings) because git says
This branch is 5 commits ahead, 19 commits behind J-Rios:master. 
https://github.com/nidamanx/TLG_JoinCaptchaBot

So, let's skip this new commit. I would like to be in sink with you.

**Review by J-Rios — COMMENTED** [review]
Ok!

That's expected due your fork just point to your remote...

- The easy solution is to delete your fork and create a new one from the original repository.

- Alternatively to avoid removing your current fork, is to clone it in your local and setup another remote (i.e. with name "original") and fetch/pull from there to get my changes, then push it to your remote:

```bash
git checkout master
git remote add original https://github.com/J-Rios/TLG_JoinCaptchaBot
git fetch original
git pull original
git push
```

Of course, it is not done automatically, so every time I make a new change you need to do it again by yourself. Maybe Github Actions could have something for this to be setup in your fork, but I'm not sure.

Normally the easy way is to delete fork and fork again ;)

**Comment by nidamanx** [comment]
@J-Rios 
I used the easy (and safest) way ;)
And now all is fine. Good.

Maybe you could update your ReadMe.md adding also my name
Thanks

P.S. this sw is really good for all the community!
Good job! :)

**Comment by J-Rios** [comment]
Nice.

> Maybe you could update your ReadMe.md adding also my name

Of course, added :)

Thank you!

**Pull request closed without merging**
