### PR TITLE
read configuration from environment variables

### PR DESCRIPTION
**Pull request by categulario**
While I was trying to setup an instance of this bot I realized that I had to modify a file in the git tree (`constants.py`). That means that there's no easy way to update the bot by just pulling new code, due to the working directory not being _clean_.

Therefore I propose this change, that allows configuration to be read from environment variables so that there's no need to modify a file in the working tree.

I would even go further by doing this:

instead of having a dictionary containing the possible setttings I would put them as top-level variables that can be imported individually:

```python
# Set if you wan't the Bot to be Public or Private
# Public: can be used by any group
# Private: just can be used in allowed groups (Bot owner allow them with /allow_group command)
BOT_PRIVATE = bool(int(os.getenv("BOT_PRIVATE", "0")))

# Bot Token (get it from @BotFather)
TOKEN = os.getenv("TOKEN", "XXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")

# Bot Owner (i.e. "@JoseTLG" or "123456789")
BOT_OWNER = os.getenv("BOT_OWNER", "XXXXXXXXX")
```
that makes the `constants.py` a little bit cleaner with the only cost of having to import all the config variables in `join_captcha_bot.py`, which is not that bad because it allows for linters do detect unused variables or misspellings.

### CODE REVIEW

**Review by J-Rios — CHANGES_REQUESTED** [review]
As you said, it is a better option to automate deployment and updates, however it increase the complexity of Bot setup, it is less user-friendly and the users needs to know about virtual environments... This PR will be accepted when some documentation regarding how to setup venv and Bot constants through envorienment variables in README file.

**Comment by patschi** [comment]
IMHO: I don't necessarily think that it "complicates bot setup", because that's how Docker/Container work. You have your application in a container, and you persist data using volumes and environment variables (while env labels/secrets are more used for defining settings/options, like database connections or so). If someone isn't able able to spin up the bot the intended way using docker, reading the docker documentation or the principle about containers is recommended anyway.

Thanks @categulario for the PR!

**Comment by J-Rios** [comment]
Then, adding a short text description and pointing with links into Docker and Virtual Environment documentations in Readme file should be enough...

However, @categulario and I have some private conversation and we both agree that maybe the first step should be make a separate configuration file (settings.py) passed to Bot launch, it is a better approach to isolate Bot config from the Bot code and also maintain simplicity in setup while avoid requesting the users to know/learn about other technologies like venv, Docker, etc.

With this approach, Bot launch will be something like:
```bash
python3 join_captcha_bot.py -c settings.py
```

After that, then we can also accept environment variables to bring flexibility of use to both, simple users and advanced-users.

**Comment by J-Rios** [comment]
Settings file and Environment Variables support added in [this commit](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/1f602edc8b52798a4c6f9221f305831cbfce02a5).

Closing this PR.

**Pull request closed without merging**
