### PR TITLE
Added Hebrew translation

### PR DESCRIPTION
**Pull request by guymass**
JSON Hebrew translation file added.

### CODE REVIEW

**Comment by guymass** [comment]
Hope this help this nice bot to get some Hebrew audience. Please let me know when I can use the language.

**Review by J-Rios — CHANGES_REQUESTED** [review]
Hi, thanks for the translation, however seems that the file is an invalid JSON format due it has some backslashes on "HELP" and "COMMANDS" texts, please check some of the texts like this one (the '\ characters is bad JSON sintax):
רשימת מזהי המשתמשים שהתעלמו מהם\\'

Should that backslashes (\) be there? are part of the hebrew alphabet or could it be removed?

Also, seems that "CAPTCHA_POLL_USAGE" text has some missing part of the text, can you check it?

Regards.

**Comment by J-Rios** [comment]
Due, not update received regarding this, let me merge and fix on my way.

**Comment by J-Rios** [comment]
The phrase added by myself in "CAPTCHA_POLL_USAGE" should be reviewed, not sure if it is ok or is reversed:

https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/50725b4bd2411d0d8a7ff1d14a0fa7a3fdcba52c

**Pull request merged**
